import os

ISSUER = os.environ.get("ISSUER", "https://changeme")
PRIVKEY = os.environ.get("PRIVKEY", '''-----BEGIN PRIVATE KEY-----
This page has been intentionally left blank
-----END PRIVATE KEY-----''')
KEYID = os.environ.get("KEYID", '''KEYID''')
CERT = os.environ.get('CERT','''-----BEGIN CERTIFICATE-----
MIIFGTCCAwGgAwIBAgIUYN8XVMv+W33sWVMv9NKfITbLydEwDQYJKoZIhvcNAQEL
BQAwHDEaMBgGA1UEAwwRYXBwQ2VydEZvckF6dXJlQUQwHhcNMjQwNjExMTMwODI3
WhcNMzQwNjA5MTMwODI3WjAcMRowGAYDVQQDDBFhcHBDZXJ0Rm9yQXp1cmVBRDCC
AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANSGlg3vB0ft30VouqIp1QIP
JluDWPfkZu0b9//tssNVM/E4TRZl3UWBV1IrQosZvI4gbFQdJMZujK4FcnlMY4KK
uGbTbRH2qcYbcBv48PPggg3KQ5Gb5zooXYap8PTZlH/1qeniDShVxXGqapzevoZ2
GR7glFEkRdNVzvT/CnSP8O9BapeYTHKSSBHNxQmkUC+TES1KzdOU3Vd8YJlep3aH
Ewa6I88vPrSrBi2OD1BKihsVWhHQCKSqwPgKBNKS03mdjKGe9QyueW9eXmotfzUI
qM3pxcMzcckDs1n/R24vN1uzd5nVK/816mOsN6RbLjNlIPAMToRLAoG7YA+LycDJ
Q+88OnXm1GbRrbtK7fOaxFPaZA8PT8bHbQcEOAer5mwZzg2Trwof+CWL0vadYNHN
sqBq/48wKI8vSVREDPAFFj4BhFh4jjVVzcOsK3qQfXNh+ivoXf+4GYYmI1INMiI/
ZNjctPPbX9YDMxhYmJR6OeyZlnV2Q6hpfm3gLoE8XpUTCqInh/pn+v6eoo32GBKK
2syU63spmsqIlLjAvT4uWwY78svK6SDj3UeiDa+I/uVJM4H0E214xhnyIKbKtL/E
jWWG6uINYBs0YU/0fwkL26Zxb90Ury3SnB/ksYCOD1H4MINvSqcX7o7qfTT2dWpS
GdFdahNceo0bGgq3HEAdAgMBAAGjUzBRMB0GA1UdDgQWBBQ1Jxtsr6pZESAEEc79
XJtKaVFHojAfBgNVHSMEGDAWgBQ1Jxtsr6pZESAEEc79XJtKaVFHojAPBgNVHRMB
Af8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQAtELuCkpDdoRl5dk87/JFdcWi5
Xv54sjiXKERYvmF1krbu838k/Vep45OqKOJNgM4yOSpyzLdP1LUcxAx09GbuiFSZ
XOwXzOFSG2z7EeBQ/vnDtyinlQ86nmBdPFCviGz3D1VGn0BRUGv91yZq23PV+pCC
Lf4QWuyLA1hb2fEnY8PbXuf1oBmDY6JbU529v3o01b+nrbTQUOn0RaLJX5Dq5LtG
BUnDDpCT7AoDFgwL3mCBEM64IYDb6r+UhccCxVGb8+gGPVWNmRr9RzWCPataQmmN
eQWdY+g9Mio/vKWYPskE/SDHwk+VIkgdurNzkbH3AhO2G2JAqizDo3KOmDhsZahM
qLwEjakK3kTvcZk1Hw3Ls5QDhJkiG2EkUGeVtVx+laZclyYNg75Le4+ZTsu0GeDc
59Sp7R01lSaLiBYckVRkhg/DATshjk3nRYkie0JdUd4LBFq3ckDZyxk4Jc4ZvDc7
+vd9YKxx7satcGu8NzGZT3G4i3AGvs2NVqV3N6WuqhuOQ6ibhJq6Qjv53wFx0Lt3
ZKpLc7LOUnCYXlwrh3vZshYo4fgBY9aZzALUDRS+08kIXsQM+4dvdMIsxldZ9okO
HO7AYw0b2O1BLKHFp7YfrwNq+xzivtSks6toj/vArJKa+8kMH7CXg0QILwJ0iJcw
DNP33NnuP5ILZSsyZg==
-----END CERTIFICATE-----''')
# Whether to enable External Auth Method capabilities for a fake MFA provider
EAMENABLED = True
# Whether to enable the "backdoor" EAM provider that injects custom keys into existing EAM provider configurations
BACKDOORENABLED = True
REALISSUER = os.environ.get("REALISSUER", "https://eu-west.azureauth.duosecurity.com")
